#!/bin/sh

# 
if [ "$CONTINUOUS_INTEGRATION" = "true" ]; then
  git push origin --dry-run --follow-tags --porcelain \
    && git push origin --follow-tags --porcelain
else
  git push origin --dry-run --follow-tags --porcelain 
fi

